### ISSUE TITLE
GCC 8.1.0 compile error

### ISSUE THREAD

**Issue by Flupper** [keirf/Disk-Utilities#59]
``
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/8.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 8.1.0 (GCC)
``

Fails to compile:
``$ caps=y make``

[snip]

``
eadf.c: In function 'eadf_close':
eadf.c:147:5: error: 'strncpy' output truncated before terminating nul copying 8 bytes from a string of the same length [-Werror=stringop-truncation]
     strncpy(dhdr.sig, "UAE-1ADF", sizeof(dhdr.sig));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [../../Rules.mk:85: eadf.opic] Error 1
make[2]: Leaving directory '/home/michael/Source/Disk-Utilities/libdisk/container'
make[1]: *** [Makefile:42: all] Error 2
make[1]: Leaving directory '/home/michael/Source/Disk-Utilities/libdisk'
make: *** [Makefile:7: all] Error 2
``

Compiles fine on GCC 7.3.1.

**Comment by Flupper** [comment]
Thanks for the fix.
